In [108]:
#https://www.kaggle.com/code/ashydv/sales-prediction-simple-linear-regression
from sklearn import linear_model
# Import the numpy and pandas package
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
import statsmodels.api as sm
import matplotlib.pyplot as plt
#import pandas_datareader.data as web
import seaborn as sns
import pandas as pd
import os.path
import numpy as np
from scipy.stats import spearmanr
import time
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report

In [109]:
start_time = time.time()

dataframe = pd.DataFrame(pd.read_csv("creditcard.csv"))
dataframe.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [110]:
dataframe.shape

(284807, 31)

In [111]:
dataframe.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,284807.000000,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,...,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,284807.000000,284807.000000
mean,94813.859575,3.918649e-15,5.682686e-16,-8.761736e-15,2.811118e-15,-1.552103e-15,2.040130e-15,-1.698953e-15,-1.893285e-16,-3.147640e-15,...,1.473120e-16,8.042109e-16,5.282512e-16,4.456271e-15,1.426896e-15,1.701640e-15,-3.662252e-16,-1.217809e-16,88.349619,0.001727
std,47488.145955,1.958696e+00,1.651309e+00,1.516255e+00,1.415869e+00,1.380247e+00,1.332271e+00,1.237094e+00,1.194353e+00,1.098632e+00,...,7.345240e-01,7.257016e-01,6.244603e-01,6.056471e-01,5.212781e-01,4.822270e-01,4.036325e-01,3.300833e-01,250.120109,0.041527
min,0.000000,-5.640751e+01,-7.271573e+01,-4.832559e+01,-5.683171e+00,-1.137433e+02,-2.616051e+01,-4.355724e+01,-7.321672e+01,-1.343407e+01,...,-3.483038e+01,-1.093314e+01,-4.480774e+01,-2.836627e+00,-1.029540e+01,-2.604551e+00,-2.256568e+01,-1.543008e+01,0.000000,0.000000
25%,54201.500000,-9.203734e-01,-5.985499e-01,-8.903648e-01,-8.486401e-01,-6.915971e-01,-7.682956e-01,-5.540759e-01,-2.086297e-01,-6.430976e-01,...,-2.283949e-01,-5.423504e-01,-1.618463e-01,-3.545861e-01,-3.171451e-01,-3.269839e-01,-7.083953e-02,-5.295979e-02,5.600000,0.000000
50%,84692.000000,1.810880e-02,6.548556e-02,1.798463e-01,-1.984653e-02,-5.433583e-02,-2.741871e-01,4.010308e-02,2.235804e-02,-5.142873e-02,...,-2.945017e-02,6.781943e-03,-1.119293e-02,4.097606e-02,1.659350e-02,-5.213911e-02,1.342146e-03,1.124383e-02,22.000000,0.000000
75%,139320.500000,1.315642e+00,8.037239e-01,1.027196e+00,7.433413e-01,6.119264e-01,3.985649e-01,5.704361e-01,3.273459e-01,5.971390e-01,...,1.863772e-01,5.285536e-01,1.476421e-01,4.395266e-01,3.507156e-01,2.409522e-01,9.104512e-02,7.827995e-02,77.165000,0.000000
max,172792.000000,2.454930e+00,2.205773e+01,9.382558e+00,1.687534e+01,3.480167e+01,7.330163e+01,1.205895e+02,2.000721e+01,1.559499e+01,...,2.720284e+01,1.050309e+01,2.252841e+01,4.584549e+00,7.519589e+00,3.517346e+00,3.161220e+01,3.384781e+01,25691.160000,1.000000

In [112]:
print(dataframe.isnull().sum())

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [113]:
names = dataframe.columns
scaler = StandardScaler()
# Fit your data on the scaler object
scaled_df = scaler.fit_transform(dataframe)
scaled_df = pd.DataFrame(dataframe, columns=names)
print(scaled_df.head())

   Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010

        V26       V27       V28  Amount  Class
0 -0.189115  0.133558 -0.021053  149.62      0
1  0.125895 -0.008983  0.014724    2.69      0
2 -0.139097 -0.055353 -0.059752  378.66      0
3 -0.221929  0.062723  0.061458  123.50      0
4  0.502292  0.219422  0.215153   69.99      0

[5 rows x 31 columns]

In [114]:
#Remove unused Time column
scaled_df.drop("Time", axis=1, inplace=True)
scaled_df.head()

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,0.090794,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,-0.166974,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,0.207643,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,-0.054952,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,0.753074,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [115]:
X = scaled_df.drop("Class", axis=1)
# Our descriptive feature
print("X.describe()")
print(X.describe())

y = scaled_df['Class']
print(y.describe())

X.describe()
                 V1            V2            V3            V4            V5  \
count  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05
mean   3.918649e-15  5.682686e-16 -8.761736e-15  2.811118e-15 -1.552103e-15
std    1.958696e+00  1.651309e+00  1.516255e+00  1.415869e+00  1.380247e+00
min   -5.640751e+01 -7.271573e+01 -4.832559e+01 -5.683171e+00 -1.137433e+02
25%   -9.203734e-01 -5.985499e-01 -8.903648e-01 -8.486401e-01 -6.915971e-01
50%    1.810880e-02  6.548556e-02  1.798463e-01 -1.984653e-02 -5.433583e-02
75%    1.315642e+00  8.037239e-01  1.027196e+00  7.433413e-01  6.119264e-01
max    2.454930e+00  2.205773e+01  9.382558e+00  1.687534e+01  3.480167e+01

                 V6            V7            V8            V9           V10  \
count  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05
mean   2.040130e-15 -1.698953e-15 -1.893285e-16 -3.147640e-15  1.772925e-15
std    1.332271e+00  1.237094e+00  1.194353e+00  1.098632e+00  1.088850e+00
min   -2.616051e+01 -4.355724e+01 -7.321672e+01 -1.343407e+01 -2.458826e+01
25%   -7.682956e-01 -5.540759e-01 -2.086297e-01 -6.430976e-01 -5.354257e-01
50%   -2.741871e-01  4.010308e-02  2.235804e-02 -5.142873e-02 -9.291738e-02
75%    3.985649e-01  5.704361e-01  3.273459e-01  5.971390e-01  4.539234e-01
max    7.330163e+01  1.205895e+02  2.000721e+01  1.559499e+01  2.374514e+01

       ...           V20           V21           V22           V23  \
count  ...  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05
mean   ...  5.126845e-16  1.473120e-16  8.042109e-16  5.282512e-16
std    ...  7.709250e-01  7.345240e-01  7.257016e-01  6.244603e-01
min    ... -5.449772e+01 -3.483038e+01 -1.093314e+01 -4.480774e+01
25%    ... -2.117214e-01 -2.283949e-01 -5.423504e-01 -1.618463e-01
50%    ... -6.248109e-02 -2.945017e-02  6.781943e-03 -1.119293e-02
75%    ...  1.330408e-01  1.863772e-01  5.285536e-01  1.476421e-01
max    ...  3.942090e+01  2.720284e+01  1.050309e+01  2.252841e+01

                V24           V25           V26           V27           V28  \
count  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05
mean   4.456271e-15  1.426896e-15  1.701640e-15 -3.662252e-16 -1.217809e-16
std    6.056471e-01  5.212781e-01  4.822270e-01  4.036325e-01  3.300833e-01
min   -2.836627e+00 -1.029540e+01 -2.604551e+00 -2.256568e+01 -1.543008e+01
25%   -3.545861e-01 -3.171451e-01 -3.269839e-01 -7.083953e-02 -5.295979e-02
50%    4.097606e-02  1.659350e-02 -5.213911e-02  1.342146e-03  1.124383e-02
75%    4.395266e-01  3.507156e-01  2.409522e-01  9.104512e-02  7.827995e-02
max    4.584549e+00  7.519589e+00  3.517346e+00  3.161220e+01  3.384781e+01

              Amount
count  284807.000000
mean       88.349619
std       250.120109
min         0.000000
25%         5.600000
50%        22.000000
75%        77.165000
max     25691.160000

[8 rows x 29 columns]
count    284807.000000
mean          0.001727
std           0.041527
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: Class, dtype: float64

In [116]:
#train_features, test_features, train_labels, test_labels = train_test_split(df_scaled, 
                                                                            #target,
                                                                          #  random_state=0, 
                                                                            #stratify=target)

print("\nLet's build our Linear regression Model\n")

X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.20, random_state=1)

print("\n(X_train.head())\n")
print("======================")
print(X_train.head())

solver = 'liblinear'
lrclf = LogisticRegression(solver=solver)
lrclf = lrclf.fit(X_train, Y_train)

#regression = linear_model.LinearRegression()
#regression.fit(X_train, Y_train)

Let's build our Linear regression Model


(X_train.head())

======================
              V1        V2        V3        V4        V5        V6        V7  \
13367   1.387525 -0.547811  0.076422 -0.739334 -0.519887 -0.026007 -0.694673
31788   1.021179 -0.194114  1.207791  1.738369 -0.659824  0.631864 -0.434168
84796  -1.134453  0.636843  2.457241  1.317848  0.605755  0.143546  0.242076
6243   -0.851343  0.062000  1.406917 -1.669375  0.462639 -0.150804  0.403887
162432 -0.040314  0.545458  0.831788 -0.515723  0.128584 -0.112466  0.027800

              V8        V9       V10  ...       V20       V21       V22  \
13367  -0.052100  0.378187  0.488238  ... -0.469630 -0.658299 -1.307286
31788   0.227422  1.116400 -0.456468  ... -0.090960 -0.386993 -0.664598
84796   0.371466 -1.315582  0.050471  ... -0.040412  0.328508  0.683118
6243    0.200460  1.968672 -1.666708  ... -0.301203 -0.400262 -1.096108
162432  0.222503  0.639397 -1.146686  ... -0.120943  0.102439  0.351638

             V23       V24       V25       V26       V27       V28  Amount
13367  -0.013221 -0.912415  0.163178  0.920997 -0.096560 -0.014846   31.35
31788   0.047173  0.106897  0.443932 -0.515898  0.091188  0.035959   41.29
84796  -0.114294  0.203942  0.035426 -0.090987  0.057247  0.102961   23.27
6243    0.023423 -0.842077 -0.301144  0.932506 -0.088128  0.076487   45.00
162432  0.180840  0.572238 -1.486248  0.147366  0.253324  0.291266    9.84

[5 rows x 29 columns]

In [117]:
print("Model Evaluation")

y_predicted = lrclf.predict(X_test)
lr_score = accuracy_score(y_predicted, Y_test)
print("Logistic Regression ({}) score: {}".format(solver, lr_score))

accuracy = accuracy_score(Y_test, y_predicted)
classification_rep = classification_report(Y_test, y_predicted)

print(f"Accuracy: {accuracy:.4f}")
print("Classification Report:")
print(classification_rep)

end_time = time.time()
time_taken = end_time - start_time
time_taken_ms = (time_taken) * 1000
print(f"Time taken for the pipeline execution: {time_taken_ms:.2f} milliseconds, {time_taken:.4f} seconds")

Model Evaluation
Logistic Regression (liblinear) score: 0.9991573329588147
Accuracy: 0.9992
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56875
           1       0.83      0.56      0.67        87

    accuracy                           1.00     56962
   macro avg       0.91      0.78      0.84     56962
weighted avg       1.00      1.00      1.00     56962

Time taken for the pipeline execution: 11126.82 milliseconds, 11.1268 seconds

In [123]:
single_row = X.iloc[[0]]
print(single_row)
lrclf.predict(single_row)

         V1        V2        V3        V4        V5        V6        V7  \
0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599

         V8        V9       V10  ...       V20       V21       V22       V23  \
0  0.098698  0.363787  0.090794  ...  0.251412 -0.018307  0.277838 -0.110474

        V24       V25       V26       V27       V28  Amount
0  0.066928  0.128539 -0.189115  0.133558 -0.021053  149.62

[1 rows x 29 columns]

array([0], dtype=int64)